# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2.3

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip gnupg
          - curl -sL https://deb.nodesource.com/setup_7.x | bash -
          - apt-get install -y nodejs
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --no-dev
          - npm install --production
          - cd ..
          - tar --exclude='.git' --exclude='Gruntfile.js' --exclude='Vagrantfile' --exclude='bitbucket-pipelines.yml' --exclude='composer.phar' --exclude='crowdin.yml.example' --exclude='behat.example.xml' --exclude='phpunit.example.xml' -czvf build.tar.gz build
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"../build.tar.gz"