<?php
$string['information block'] = '1Information Block';
$string['keywordbasedquestion'] = '1Keyword-based Question';
$string['random question block'] = '1Random Question Block';
$string['calculation'] = '1Calculation';
$string['dichotomous'] = '1Dichotomous (Yes/No and True/False)';
$string['extended matching'] = '1Extended Matching';
$string['fill-in-the-blank'] = '1Fill-in-the-Blank';
$string['flash'] = '1Flash Interface';
$string['image hotspot'] = '1Image Hotspot';
$string['labelling'] = '1Labelling';
$string['likert scale'] = '1Likert Scale';
$string['matrix'] = '1Matrix';
$string['multiple choice'] = '1Multiple Choice (MCQ)';
$string['multiple response'] = '1Multiple Response (MRQ)';
$string['ranking'] = '1Ranking';
$string['sct'] = '1Script Concordance Test (SCT)';
$string['text box'] = '1Text Box';
$string['time/date'] = '1Time/Date';

?>