<?php
$string['info'] = '1Information Block';
$string['keyword_based'] = '1Keyword-based Question';
$string['random'] = '1Random Question Block';
$string['calculation'] = '1Calculation';
$string['dichotomous'] = '1Dichotomous';
$string['extmatch'] = '1Extended Matching';
$string['blank'] = '1Fill-in-the-Blank';
$string['flash'] = '1Flash Interface';
$string['hotspot'] = '1Image Hotspot';
$string['labelling'] = '1Labelling';
$string['likert'] = '1Likert Scale';
$string['matrix'] = '1Matrix';
$string['mcq'] = '1Multiple Choice (MCQ)';
$string['mrq'] = '1Multiple Response (MRQ)';
$string['rank'] = '1Ranking';
$string['sct'] = '1Script Concordance Test (SCT)';
$string['textbox'] = '1Text Box';
$string['timedate'] = '1Time/Date';

?>