<?php
// This file is part of Rogo
//
// Rogo is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Rogo is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Rogo.  If not, see <http://www.gnu.org/licenses/>.

$string['home'] = 'Strona główna';
$string['help'] = 'Pomoc';
$string['line'] = 'Linia';
$string['cancel'] = 'Anuluj';
$string['ok'] = 'OK'; //cognate
$string['save'] = 'Zachowaj';
$string['accessdenied'] = 'Odmowa dostępu';
$string['accessdeniedadmin'] = '<strong>Brak dostępu</strong><br />Podejmujesz działania dostępne tylko administratorowi.';
$string['accessdeniedsysadmin'] = '<strong>Brak dostępu</strong><br />Podejmujesz działania dostępne tylko administratorowi systemu.';
$string['denied_paper'] = 'Nie posiadasz  <strong>praw dostępu do tego arkusza</strong>!';
$string['denied_folder'] = 'Nie posiadasz  <strong>praw dostępu do tego folderu</strong>!';
$string['denied_question'] = 'Nie posiadasz  <strong>praw dostępu do tego pytania</strong>!';
$string['denied_team'] = 'Nie jesteś członkiem zespołu dla modułu <strong>%s</strong>.';
$string['noldapusernamesupplied'] = 'Nie wprowadzono loginu lub hasła LDAP';
$string['incorrectpassword'] = 'Wprowadzono nieprawidłowe hasło';
$string['ldapserverunavailable'] = 'Serwer LDAP jest niedostępny';
$string['noldapaccount'] = 'Nie odnaleziono konta LDAP !';
$string['ldapservernosearch'] = 'Serwer LDAP niedostępny: wyszukiwanie niemożliwe';
$string['nodatabaseconnection'] = 'Podłączenie do bazy niemożliwe - skontaktuj się z administratorem';
$string['as'] = 'jako';
$string['localtsauthfailed'] = 'Nie uzyskano uwierzytelniania Rogō.';
$string['notsaccount'] = 'Nie odnaleziono konta Rogō!';
$string['tempaccount'] = 'Konto tymczasowe';
$string['authenticationfailed'] = 'Nie uzyskano uwierzytelnienia Rogō, należy pamiętać:';
$string['usernamecasesensitive'] = 'W loginie i haśle rozróżniane są duże i małe litery';
$string['pressf5'] = "Wybierz 'F5' na klawiaturze aby logować się ponownie";
$string['tsonldap'] = 'W Rogō stosowane są hasła LDAP';
$string['ifstuckinvigilator'] = 'W razie dalszych problemów poproś osobę nadzorującą o';
$string['forgottenpassword'] = 'Zapomniane hasło';
$string['warning'] = 'Uwaga:';
$string['secureconnection'] = 'Wymagane bezpieczne połączenie';  
$string['secureconnectionmsg'] = 'Rogō jest dostępny wyłącznie przez połączenie bezpieczne. W zamian użyj:';
$string['errormsg'] = 'Jeśli kolejny raz napotkałeś ten błąd skontaktuj się z:';
$string['ltifirstlogin'] = 'Autoryzacja Rogō';
$string['ltifirstlogindesc'] = 'System egzaminowania Rogō wymaga identyfikacji Twojej osoby, aby upewnić się co do posiadanych przez Ciebie przywilejów. Dokonane to będzie tylko przy pierwszej wizycie i w nielicznych przypadkach, w celu zapewnienia bezpieczeństwa w przyszłości.<br /><a href="./">Kliknij, aby kontynuować</a> ';
$string['ltinotconfigured'] = 'Hiperłącze, które wybrałeś nie jest jeszcze skonfigurowane.';  
$string['LTIFAILURE'] = 'niepowodzenie LTI';
$string['expiredtimestamp'] = 'Datownik tego połączenia jest już przeterminowany. Powróć do poprzedniej strony i ponownie wybierz ten link (nie odświeżaj przeglądarki).';
$string['UserMissing']='Brak stowarzyszonego użytkownika ';  
$string['UserMissingDesc'] = 'Z jakiegoś powodu w systemie Rogo brak jest stowarzyszonego użytkownika. To jest poważny błąd dlatego powinieneś skontaktować się z administratorem systemu'; 
?>
