<?php
$string['formative self-assessment'] = 'Formatywna samoocena';
$string['progress test'] = 'Test postępów';
$string['summative exam'] = 'Egzamin końcowy';
$string['survey'] = 'Ankieta';
$string['osce station'] = 'Stacja OSCE';
$string['offline paper'] = 'Arkusz Offline';
$string['formative self-assessments'] = 'Formatywne samooceny';
$string['progress tests'] = 'Testy postępów';
$string['summative exams'] = 'Egzaminy końcowe';
$string['surveys'] = 'Ankiety';
$string['osce stations'] = 'Stacje OSCE';
$string['offline papers'] = 'Arkusze Offline';
$string['peer review'] = 'Recenzja wewnętrzna';
$string['description0'] = 'Self-assessment quizzes that be normally be accessed by students at any time.';  // Niko, here downward please
$string['description1'] = 'Normally used for mid-term tests where feedback is not provided at the end of the assessment.';
$string['description2'] = "High-stakes exams where marks contribute to a student\'s course.";
$string['description3'] = 'A questionnaire used for eliciting views and feedback from students.';
$string['description4'] = 'Objective Structured Clinical Examination (OSCE) assessment type used for medical and health sciences fields.';
$string['description5'] = 'This paper type allows marks from offline papers to be loaded into Rogo.';
$string['description6'] = 'Generates a form for students to review their peers.';
?>