<?php
$string['formative self-assessment'] = '1Formative Self-Assessment';
$string['progress test'] = '1Progress Test';
$string['summative exam'] = '1Summative Exam';
$string['survey'] = '1Survey';
$string['osce station'] = '1OSCE Station';
$string['offline paper'] = '1Offline Paper';
$string['formative self-assessments'] = '1Formative Self-Assessments';
$string['progress tests'] = '1Progress Tests';
$string['summative exams'] = '1Summative Exams';
$string['surveys'] = '1Surveys';
$string['osce stations'] = '1OSCE Stations';
$string['offline papers'] = '1Offline Papers';
?>