<?php
$string['anytype'] = '(każdy typ)';
$string['info'] = 'Blok informacji';
$string['keyword_based'] = 'Pytanie bazujące na słowie kluczowym';
$string['random'] = 'Blok pytań losowych';
$string['calculation'] = 'Pytanie obliczeniowe';
$string['dichotomous'] = 'Pytanie rozróżniające';
$string['extmatch'] = 'Rozszerzone pytanie na dopasowanie';
$string['blank'] = 'Pytanie z luką';
$string['flash'] = 'Pytanie z interfejsem Flash';
$string['hotspot'] = 'Pytanie z obiektem aktywny (Hotspot obrazowy)';
$string['labelling'] = 'Pytanie na uzupełnienie z etykietą graficzną';
$string['likert'] = 'Skala Likerta';
$string['matrix'] = 'Macierz';
$string['mcq'] = 'Pytanie wielokrotnego wyboru';
$string['mrq'] = 'Pytanie z wieloma odpowiedziami';
$string['rank'] = 'Pytanie na stopniowanie';
$string['sct'] = 'Test zgodności ze skryptem';//??
$string['textbox'] = 'Pytanie półotwarte';
?>