<?php
$string['anytype'] = '(każdy typ)';
$string['info'] = 'Blok informacji';
$string['keyword_based'] = 'Pytanie bazujące na słowie kluczowym';
$string['random'] = 'Blok pytań losowych';
$string['calculation'] = 'Obliczenia';
$string['dichotomous'] = 'Rozdzielające';
$string['extmatch'] = 'Rozszerzone dopasowanie';
$string['blank'] = 'Z luką';
$string['flash'] = 'Z interfejsem Flash';
$string['hotspot'] = 'Obiekt aktywny (Hotspot obrazowy)';
$string['labelling'] = 'Etykiety graficzne (Labelling)';
$string['likert'] = 'Skala Likerta';
$string['matrix'] = 'Macierz';
$string['mcq'] = 'Wielokrotnego wyboru';
$string['mrq'] = 'Wielu odpowiedzi';
$string['rank'] = 'Stopniowanie';
$string['sct'] = 'Test zgodności skryptu';//??
$string['textbox'] = 'Pole tekstowe';
?>