<?php
$string['anytype'] = '(każdy typ)';
$string['info'] = 'Blok informacji';
$string['keyword_based'] = 'Pytanie bazujące na słowie kluczowym';
$string['random'] = 'Blok pytań losowych';
$string['calculation'] = 'P. obliczeniowe';
$string['dichotomous'] = 'P. rozróżniające';
$string['extmatch'] = 'Rozszerzone p. na dopasowanie';
$string['blank'] = 'P. z luką';
$string['flash'] = 'P. z interfejsem Flash';
$string['hotspot'] = 'P. z obiektem aktywny (Hotspot obrazowy)';
$string['labelling'] = 'P na uzupełnienie z etykietą graficzną';
$string['likert'] = 'Skala Likerta';
$string['matrix'] = 'Macierz';
$string['mcq'] = 'P. wielokrotnego wyboru';
$string['mrq'] = 'P. z wieloma odpowiedziami';
$string['rank'] = 'P. na stopniowanie';
$string['sct'] = 'Test zgodności skryptu';//??
$string['textbox'] = 'P. półotwarte';
?>