<?php
require '../lang/' . $language . '/include/months.inc';
$string['moreinformation'] = 'Więcej informacji';
$string['viewdetails'] = 'Ogląd szczegółów';
$string['debuginformation'] = 'Informacje dot. błędów';
$string['loadingdebug'] = 'Wyszukiwanie błędów ładowania';
$string['intermediateformatdebug'] = 'Wyszukiwanie błędów pośrednich';
$string['savingdebug'] = 'Zapisywanie wyników wyszukiwania błędów';
$string['generaldebuginfo'] = 'Ogólne informacje dot. błędów';
// Niko
$string['addingtopaper'] = 'Adding to paper';
$string['params'] = 'Params';
$string['othherdebug'] = 'Other Debug';
$string['noquestions'] = 'No questions to load into Rogo';
$string['questiontables'] = 'Question Tables';
$string['questionsrow'] = 'questions row';
$string['optionsrows'] = 'options rows';
$string['newkeywords'] = 'new keywords';
$string['addingquestiondetails'] = 'adding question %d as display_pos = %d on screen %d';
