name: Translations
on:
  push:
    branches:
      - develop
jobs:
  crowdin:
    # This job should only run in the main repository.
    if: ${{ github.repository == 'examsys/examsys' }}
    name: Update Crowdin develop branch
    runs-on: ubuntu-latest

    env:
      # A numeric ID, found at https://crowdin.com/project/<projectName>/tools/api
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}

      # Visit https://crowdin.com/settings#api-key to create this token
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Lint config file
        uses: crowdin/github-action@v3
        with:
          command: 'config lint'

      - name: Push to Crowdin develop branch
        uses: crowdin/github-action@v3
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          push_translations: false
          push_sources: false
          create_pull_request: false
          upload_sources_args: --branch=develop
